name: Publish

on: [workflow_dispatch]

jobs:
  publish:
    runs-on:  macos-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
      - name: Setup gradle
        uses: gradle/gradle-build-action@v3
      - name: Write Secrets
        uses: "DamianReeves/write-file-action@master"
        with:
          path: ./gradle.propertis
          write-mode: append
          contents: |
            echo "mavenCentralUsername=${{ secrets.MAVENCENTRALPASSWORD }}"
            echo "mavenCentralPassword=${{ secrets.MAVENCENTRALUSERNAME }}"
            echo "signing.keyId=${{ secrets.SIGNINGKEYID }}"
            echo "signing.password=${{ secrets.SIGNINPASSWORD }}"
      - name: Publish to Maven Central
        run: ./gradlew publishAllPublicationsToMavenCentral --no-configuration-cache

  
